spring:
  application:
    name: customer
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: simon
    password: simon
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:password@eureka:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "health,beans"
logging:
  level:
    root: INFO
  file:
    name: application.log