apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  serviceName: "eureka"
  podManagementPolicy: "Parallel" 
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka    
    spec:
      containers:
      - name: eureka
        image: sjo0911/eureka
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: carsapp
spec:
  ports:
  - port: 8761
    name: eureka-123
    protocol: TCP
    targetPort: http
  selector:
    app: "carsapp"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  type: NodePort
  ports:
  - port: 8761
    nodePort: 30030
    name: eureka
  selector:
    app: eureka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: carsapp
  name: cars
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carsapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: carsapp
    spec:
      containers:
      - image: sjo0911/cars
        name: cars
        resources: {}
status: {}
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: carsapp
  name: booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carsapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: carsapp
    spec:
      containers:
      - image: sjo0911/booking
        name: booking
        resources: {}
status: {}
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: carsapp
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carsapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: carsapp
    spec:
      containers:
      - image: sjo0911/customer
        name: customer
        resources: {}
status: {}
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: carsapp
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carsapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: carsapp
    spec:
      containers:
      - image: sjo0911/order
        name: order
        resources: {}
status: {}
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: carsapp
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carsapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: carsapp
    spec:
      containers:
      - image: sjo0911/gateway
        name: gateway
        resources: {}
status: {}
---    
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8087
  selector:
    app: carsapp