server:
  port: 8087

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: '*'
            allowed-methods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "HEAD"
              - "OPTIONS"
            allowed-headers:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "User-Key"
              - "Request-Tracker"
              - "Session-Tracker"
              - "X-XSRF-TOKEN"
              - "X-IBM-CLIENT-ID"
              - "Message-ID"
              - "X-IBM-CLIENT-SECRET"
        add-to-simple-url-handler-mapping: true
      routes:
        - id: bookingModule
          uri: lb://BOOKING
          predicates:
            - Path=/api/v1/ordercar
            - Method=POST
          filters:
            - RewritePath=/api/v1/ordercar(?<RID>.*), /api/v1/booking/$\{RID}
        - id: bookingModule
          uri: lb://BOOKING
          predicates:
            - Path=/api/v1/updateorder/**
            - Method=PUT
          filters:
            - RewritePath=/api/v1/updateorder(?<RID>.*), /api/v1/booking/$\{RID}
        - id: bookingModule
          uri: lb://BOOKING
          predicates:
            - Path=/api/v1/myorders/**
            - Method=GET
          filters:
            - RewritePath=/api/v1/myorders(?<RID>.*), /api/v1/booking/customersbooking/$\{RID}
        - id: customerModule
          uri: lb://customer
          predicates:
            - Path=/api/v1/customers/**
            - Method=GET
          filters:
            - RewritePath=/api/v1/customers(?<RID>.*), /api/v1/customer/$\{RID}
        - id: customerModule
          uri: lb://customer
          predicates:
            - Path=/api/v1/singlecustomer/**
            - Method=GET
          filters:
            - RewritePath=/api/v1/singlecustomer(?<RID>.*), /api/v1/singlecustomer/$\{RID}
        - id: orderModule
          uri: lb://order-api
          predicates:
            - Path=/api/v1/cars/**
            - Method=GET
          filters:
            - RewritePath=/api/v1/cars(?<RID>.*), /api/v1/cars/$\{RID}
        - id: carModule
          uri: lb://cars
          predicates:
            - Path=/api/v1/addcar
            - Method=POST
          filters:
            - RewritePath= /api/v1/addcar(?<RID>.*), /api/v1/car/$\{RID}
        - id: carModule
          uri: lb://cars
          predicates:
            - Path=/api/v1/getcar/**
            - Method=GET
          filters:
            - RewritePath= /api/v1/getcar(?<RID>.*), /api/v1/car/$\{RID}
        - id: orderModule
          uri: lb://order-api
          predicates:
            - Path=/api/v1/deletecar/**
            - Method=DELETE
          filters:
            - RewritePath=/api/v1/deletecar(?<RID>.*), /api/v1/cars/$\{RID}
        - id: carModule
          uri: lb://cars
          predicates:
            - Path=/api/v1/updatecar
            - Method=PUT
          filters:
            - RewritePath=/api/v1/updatecar(?<RID>.*), /api/v1/car/$\{RID}
        - id: orderModule
          uri: lb://order-api
          predicates:
            - Path=/api/v1/customerswithnumberoforders/**
            - Method=GET
          filters:
            - RewritePath=/api/v1/customerswithnumberoforders(?<RID>.*), /api/v1/customers/$\{RID}