server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:password@eureka:8761/eureka
spring:
  application:
    name: ORDER-API
management:
  endpoints:
    web:
      exposure:
        include: "*"