server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
spring:
  application:
    name: ORDER-API
management:
  endpoints:
    web:
      exposure:
        include: "health,beans"